services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./logs:/app/logs
      - /home/jiag/.sdkman/candidates/gradle/current/bin/gradle:/root/.gradle
    networks:
      - elk

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    ports:
      - "9200:9200"
    environment:
      - ELASTIC_PASSWORD=rootuser
      - KIBANA_PASSWORD=rootuser
      - discovery.type=single-node
      - xpack.security.http.ssl.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
    volumes:
      - ./elk/data:/usr/share/elasticsearch/data
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.0
    volumes:
      - ./elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=rootuser
      - ELASTIC_HOSTS=http://elastic:9200
    depends_on:
      - elastic
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: '["http://elastic:9200"]'
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: rootuser
    ports:
      - "5601:5601"
    depends_on:
      - elastic
    networks:
      - elk

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.16.2
    #command: filebeat -e -strict.perms=false
    volumes:
      - ./elk/filebeat.yaml:/usr/share/filebeat/filebeat.yml
      - ./logs:/var/log/server
    networks:
      - elk
networks:
  elk:
      driver: bridge
